server:
  port: 8888
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      min-spare: 5
      max: 50

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_REPO_URL:https://github.com/talgat-alimbayev/config-repo}
          default-label: main
          clone-on-start: true
          force-pull: true
          timeout: 5

