server:
  port: 8888
  tomcat:
    connection-timeout: 2s
    keep-alive-connection: 15s
    threads:
      max: 50
      min-spare: 5

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git: https://github.com/talgat-alimbayev/config-service
        default-label: main